version: '3.8'

services:
  # Main market maven service
  market-maven:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-maven
    environment:
      - ENVIRONMENT=production
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ENABLE_DRY_RUN=false
      - LOG_LEVEL=INFO
      - METRICS_PORT=8000
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://marketmaven:marketmaven_password@postgres:5432/marketmaven
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - market-maven-network
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "python", "-c", "import market_maven; print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: market-maven-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - market-maven-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: market-maven-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - market-maven-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: market-maven-redis
    ports:
      - "6379:6379"
    networks:
      - market-maven-network

  # PostgreSQL for data storage
  postgres:
    image: postgres:15-alpine
    container_name: market-maven-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-marketmaven}
      - POSTGRES_USER=${POSTGRES_USER:-marketmaven}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-marketmaven_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - market-maven-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: market-maven-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - market-maven-network
    depends_on:
      - market-maven

networks:
  market-maven-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres_data: 