version: '3.8'

services:
  app:
    build: .
    container_name: market-maven-app
    environment:
      - ENVIRONMENT=development
      - DATABASE_PATH=/app/data/market_maven.db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    ports:
      - "8000:8000"
    command: uvicorn market_maven.api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  data: